### ISSUE TITLE
Netowrk AI serivce problem

### ISSUE THREAD

**Issue by davins90** [RihabFekii/StreamlitApp#1]
Hi :) thanks for this great example! I have only one question: what is and how to use the network "AI service" that is written in the docker-compose.yml file? I try to reproduce your example in my PC but i get this error:

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
network AIservice declared as external, but could not be found

thanks

**Comment by RihabFekii** [comment]
Hi :) I get your problem, try to first create the AI service network by running this command: 
` $ docker network create AIservice`
Then run the docker-compose up and all the other steps mentioned in the README. 
Let me know if that solves it!

**Comment by davins90** [comment]
Hi Rihab, thanks a lot for your precious answer! Now it's everything working perfectly, thanks! I have only a little problem with using jupyterlab in the "backend" section. Do you have any suggestions?
