### ISSUE TITLE
Doubt on the front end main.py

### ISSUE THREAD

**Issue by AndrewLaganaro** [RihabFekii/StreamlitApp#2]
This project is simply a piece of art.

I'd like to know what you've done on the front end on line 493:
```
if choices == 'Prediction':
    st.header("Real-time prediction")
    default_id ="urn:ngsi-ld:WaterPotabilityMetrics:<id>"
```
What is this **default_id**? how to explain it? this is the definition of the variable but I don't get it how it works and how it fits on the project. thanks!

**Comment by RihabFekii** [comment]
Check Lines 208-211 in main.py 
Maybe it was not clear that there is a Context Broker used to get data which is used as an input of the AI model. This Context Broker has a digital twin of a particular water tank and you need to access a particular entity in it through the id.

**Comment by AndrewLaganaro** [comment]
Thanks, I'll take a look and come back if some doubts arise!
